# Generated by Django 3.2.4 on 2021-06-15 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(blank=True, max_length=40)),
                ('roles', multiselectfield.db.fields.MultiSelectField(choices=[('submitter', 'Submitter'), ('developer', 'Developer'), ('manager', 'Manager'), ('admin', 'Admin')], default='submitter', max_length=33)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
