# Generated by Django 5.1.5 on 2025-01-15 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def load_initial_data(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    data = [
        {"id": 1, "role": "submitter"},
        {"id": 2, "role": "developer"},
        {"id": 3, "role": "manager"},
        {"id": 4, "role": "admin"},
    ]
    for record in data:
        Role.objects.create(**record)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github", models.CharField(blank=True, max_length=80)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("roles", models.ManyToManyField(to="accounts.role")),
            ],
        ),
        migrations.RunPython(load_initial_data),
    ]
